image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean install
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master